version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: online-store-db
    environment:
      POSTGRES_DB: onlinestore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build: ./backend
    container_name: online-store-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/onlinestore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  # React Frontend
  frontend:
    build: ./frontend
    container_name: online-store-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: